# Generated by Django 5.1.4 on 2025-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_profile_github_profile_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
