# Generated by Django 5.1.4 on 2025-01-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.TextField(null=True),
        ),
    ]
