# Generated by Django 5.1.4 on 2025-01-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_github',
            field=models.URLField(null=True),
        ),
    ]
