# Generated by Django 5.1.4 on 2025-11-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_profile_about_me_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.AddField(
            model_name='project',
            name='detail_description',
            field=models.TextField(blank=True, help_text='Full HTML description for the project detail page.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hero_text',
            field=models.CharField(blank=True, help_text='Hero section intro shown at the top of the project detail page.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='list_summary',
            field=models.TextField(blank=True, help_text='Short blurb shown in the project list/grid.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='pypi_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_me_intro',
            field=models.TextField(blank=True, help_text='Extended introduction for the About Me page.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(help_text='Short bio displayed on the portfolio home page.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.TextField(blank=True, help_text='Short intro shown at the start of the About Me section.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.TextField(blank=True, help_text='List of skills or technologies.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.TextField(blank=True, help_text='Skills or technologies used in this project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
