# Generated by Django 5.1.4 on 2025-11-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='hero_text',
            field=models.TextField(blank=True, help_text='Hero section intro shown at the top of the project detail page.', null=True),
        ),
    ]
