# Generated by Django 5.1.4 on 2025-11-27 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_project_hero_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, help_text='Link to GitHub profile.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Link to LinkedIn profile.', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number.', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile image displayed on the portfolio site.', null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional thumbnail image for the project page or project list.', null=True, upload_to='project_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(blank=True, help_text='URL to the live website or interactive demo for this project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_github',
            field=models.URLField(blank=True, help_text='Link to the GitHub repository for this project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='pypi_url',
            field=models.URLField(blank=True, help_text="Link to the project's PyPI package (if applicable).", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL slug for the project's detail page (auto-generated if left empty).", max_length=200, null=True, unique=True),
        ),
    ]
