# Generated by Django 5.2.8 on 2026-09-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_profile_github_alter_profile_linkedin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Display this project in the featured projects section.'),
        ),
    ]
